# WARNING - Generated by {fusen} from /dev/flat_main.Rmd: do not edit by hand

test_that("fm_generate_graphs works", {
  
  # test with k = 0.25 by default
  if(Sys.getenv("FISHMAP_K_PARAM") != ""){
    k <- as.numeric(Sys.getenv("FISHMAP_K_PARAM"))
  }else{
    k <- 0.25
  }
  
  # run part1
  survey_data_file <- system.file("original_data",
                                  "Solea_solea",
                                  "survey_data.Rdata",
                                  package = "FishMap"
  )
  
  vmslogbook_data_file <- system.file("original_data",
                                      "Solea_solea",
                                      "vmslogbook_data.Rdata",
                                      package = "FishMap"
  )
  
  study_domain_file <- system.file("original_data",
                                   "Solea_solea",
                                   "study_domain.Rdata",
                                   package = "FishMap"
  )
  
  fm_data_inputs <- fm_load_data(species = "Solea_solea",
                                 fleet = c("OTB_DEF_>=70_0","OTB_CEP_>=70_0","OTT_DEF_>=70_0"),
                                 fitted_data = "biomass",
                                 survey_data_file = survey_data_file,
                                 vmslogbook_data_file = vmslogbook_data_file,
                                 study_domain_file = study_domain_file,
                                 year_start = 2018,
                                 year_end = 2018,
                                 month_start = 11,
                                 month_end = 11,
                                 time_step = "Month",
                                 k = k,
                                 grid_xmin = -6,
                                 grid_xmax = 0,
                                 grid_ymin = 42,
                                 grid_ymax = 48)
  
  # run part2
  fm_model_results <- fm_fit_model(fm_data_inputs)
  
  # run part3
  fm_graph_results <- fm_generate_graphs(fm_model_results)
  
  # save part3 outputs
  if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS") == "TRUE") {
    # setup save dir, create it if necessary
    output_dir <- Sys.getenv("FISHMAP_OUTPUT_DIR")
    if (isFALSE(dir.exists(output_dir))){
      dir.create(output_dir)
    }
    # save output
    saveRDS(object = fm_model_results, file = file.path(output_dir, "part3_output.rds"))
  }
  
  # check output is a list
  expect_true(object = inherits(x = fm_model_results,
                                what = "list"))
  
  # check pred_plot output is a ggplot object
  expect_equal(object = class(fm_graph_results[["pred_plot"]]),
               expected = c("gg", "ggplot"))
  
  # check output is saved as rds
  if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS") == "TRUE") {
    output_dir <- Sys.getenv("FISHMAP_OUTPUT_DIR")
    expect_true(file.exists(file.path(output_dir, "part3_output.rds")))
  }
  
})
