# WARNING - Generated by {fusen} from /dev/flat_fm_load_data.Rmd: do not edit by hand

test_that("fm_build_domain_mesh_spde works", {
  
  ## prepare inputs
  # vms data - unfiltered
  vmslogbook_data_file <- system.file("original_data",
                                      "Solea_solea",
                                      "vmslogbook_data.Rdata",
                                      package = "FishMap"
  )
  load(vmslogbook_data_file)
  
  # filter vms data as done in `fm_load_data()`
  fleet <- c("OTB_DEF_>=70_0","OTB_CEP_>=70_0","OTT_DEF_>=70_0")
  select_aggreg_level <- paste(fleet,collapse = "|")
  vmslogbook_data <- vmslogbook_data %>%
    filter(str_detect(LE_MET_level6,select_aggreg_level))
  vmslogbook_data$LE_MET_level6 <- factor(as.character(vmslogbook_data$LE_MET_level6),levels = fleet)
  vmslogbook_data_0 <- vmslogbook_data %>% ungroup %>% dplyr::select(-layer)
  
  # study domain
  study_domain_file <- system.file("original_data",
                                   "Solea_solea",
                                   "study_domain.Rdata",
                                   package = "FishMap"
  )
  load(study_domain_file)
  
  # mesh grid
  grid_limit <- raster::extent(c(-6, 0, 42, 48))
  
  ## run function
  result <- fm_build_domain_mesh_spde(
    grid_limit = grid_limit,
    resol = 0.05,
    grid_projection = "+proj=longlat +datum=WGS84",
    study_domain = study_domain,
    create_mesh = "from_shapefile",
    k = 0.25,
    vmslogbook_data,
    study_domain_sf = NULL,
    Alpha = 2)
  
  # test outputs
  #' @description Testing that fm_build_domain_mesh_spde returns a list
  expect_type(object = result,
              type = "list")
  
  #' @description Testing names of the list
  expect_named(object = result,
               expected = c("mesh",
                            "loc_x",
                            "spde",
                            "Aix_ij_pred",
                            "Aix_w_pred",
                            "W",
                            "MeshList_aniso",
                            "gridpolygon_sf")
  )
  
  #' @description Testing types inside the list
  expect_type(result[["mesh"]], "list")
  expect_type(result[["loc_x"]], "list")
  expect_type(result[["spde"]], "list")
  expect_type(result[["Aix_ij_pred"]], "integer")
  expect_type(result[["Aix_w_pred"]], "double")
  expect_type(result[["W"]], "double")
  expect_type(result[["MeshList_aniso"]], "list")
  expect_type(result[["gridpolygon_sf"]], "list")
}
)
