# WARNING - Generated by {fusen} from /dev/flat_fm_load_data.Rmd: do not edit by hand

test_that("fm_shape_vms_logbook_data_st works", {

  ## prepare inputs
  # vms data - unfiltered
  vmslogbook_data_file <- system.file("original_data",
                                      "Solea_solea",
                                      "vmslogbook_data.Rdata",
                                      package = "FishMap"
  )
  load(vmslogbook_data_file)
  
  # filter vms data as done in `fm_load_data()`
  fleet <- c("OTB_DEF_>=70_0","OTB_CEP_>=70_0","OTT_DEF_>=70_0")
  select_aggreg_level <- paste(fleet,collapse = "|")
  vmslogbook_data <- vmslogbook_data %>%
    filter(str_detect(LE_MET_level6,select_aggreg_level))
  vmslogbook_data$LE_MET_level6 <- factor(as.character(vmslogbook_data$LE_MET_level6),levels = fleet)
  vmslogbook_data_0 <- vmslogbook_data %>% ungroup %>% dplyr::select(-layer)
  
  # study domain
  study_domain_file <- system.file("original_data",
                                   "Solea_solea",
                                   "study_domain.Rdata",
                                   package = "FishMap"
  )
  load(study_domain_file)

  # mesh grid
  grid_limit <- raster::extent(c(-6, 0, 42, 48))
  
  # `fm_build_domain_mesh_spde()` call
  domain_mesh_spde_outputs <- fm_build_domain_mesh_spde(
    grid_limit = grid_limit,
    resol = 0.05,
    grid_projection = "+proj=longlat +datum=WGS84",
    study_domain = study_domain,
    create_mesh = "from_shapefile",
    k = 0.25,
    vmslogbook_data,
    study_domain_sf = NULL,
    Alpha = 2)
  
  # time df
  year_vec <- 2018:2018
  month_vec <- 11:11
  time.step_df <- expand.grid(month_vec,year_vec)
  colnames(time.step_df) <- c("Month","Year")
  time.step_df <- time.step_df %>%
    arrange(Year,Month) %>%
    mutate(Month = ifelse(Month < 10,paste0("0",Month),Month)) %>%
    mutate(Year_Month = paste0(Year,"_",Month)) %>%
    mutate(t = 1:nrow(time.step_df))
  time.step_df$Year <- as.character(time.step_df$Year)
  time.step_df$Month <- as.character(time.step_df$Month)
    
  ## run function
  result <- fm_shape_vms_logbook_data_st(
    vmslogbook_data_0 = vmslogbook_data_0,
    time.step_df = time.step_df,
    grid_projection = "+proj=longlat +datum=WGS84",
    gridpolygon_sf = domain_mesh_spde_outputs[["gridpolygon_sf"]],
    loc_x = domain_mesh_spde_outputs[["loc_x"]],
    mesh = domain_mesh_spde_outputs[["mesh"]]
)
  
  ## test outputs
  #' @description Testing that fm_shape_sci_data_st returns a list
  expect_type(object = result,
              type = "list")
  
  #' @description Testing names of the list
  expect_named(object = result,
               expected = c("b_com_i",
                            "y_com_i",
                            "c_com_x",
                            "t_com_i",
                            "Aix_ij_com",
                            "Aix_w_com", 
                            "vmslogbook_data_2"
                            )
               )
  
  #' @description Testing types inside the list
  expect_type(result[["b_com_i"]], "double")
  expect_type(result[["y_com_i"]], "double")
  expect_type(result[["c_com_x"]], "double")
  expect_type(result[["t_com_i"]], "integer")
  expect_type(result[["Aix_ij_com"]], "integer")
  expect_type(result[["Aix_w_com"]], "double")
  expect_type(result[["vmslogbook_data_2"]], "list")

})
