# WARNING - Generated by {fusen} from /dev/flat_fm_fit_model.Rmd: do not edit by hand

test_that("fm_build_data_params_map", {
  
  ## Settings all params
  
  SE <- 1
  data_source <- 1
  data_obs <- 2
  samp_process <- 0
  b_constraint <- 2
  const_spphab <- 1
  cov_samp_process <- 0
  biomass_temporal <- 1
  sampling_temporal <- 0
  anisotropy <- 0
  lf_link <- 0
  ref_data <- "com"
  EM <- "est_b"
  month_ref <- 1
  compute_sd <- FALSE
  
  fm_data_inputs <- readr::read_rds(system.file("examples", "part1_output_small.rds", package = "FishMap"))
  
  species <- fm_data_inputs[["species"]]
  b_com_i <- fm_data_inputs[["b_com_i"]]
  mesh <- fm_data_inputs[["mesh"]]
  time.step_df <- fm_data_inputs[["time.step_df"]]
  loc_x <- fm_data_inputs[["loc_x"]]
  y_com_i <- fm_data_inputs[["y_com_i"]]
  y_sci_i <- fm_data_inputs[["y_sci_i"]]
  cov_x_com <- fm_data_inputs[["cov_x_com"]]
  cov_x_sci <- fm_data_inputs[["cov_x_sci"]]
  c_com_x <- fm_data_inputs[["c_com_x"]]
  t_com_i <- fm_data_inputs[["t_com_i"]]
  t_sci_i <- fm_data_inputs[["t_sci_i"]]
  spde <- fm_data_inputs[["spde"]]
  Aix_ij_com <- fm_data_inputs[["Aix_ij_com"]]
  Aix_w_com <- fm_data_inputs[["Aix_w_com"]]
  Aix_ij_sci <- fm_data_inputs[["Aix_ij_sci"]]
  Aix_w_sci <- fm_data_inputs[["Aix_w_sci"]]
  cov_x_pred <- fm_data_inputs[["cov_x_pred"]]
  Aix_ij_pred <- fm_data_inputs[["Aix_ij_pred"]]
  Aix_w_pred <- fm_data_inputs[["Aix_w_pred"]]
  W <- fm_data_inputs[["W"]]
  n_survey <- fm_data_inputs[["n_survey"]]
  MeshList_aniso <- fm_data_inputs[["MeshList_aniso"]]
  
  xfb_x <- NULL # TO DELETE
  weights_com <- 1 # TO DELETE
  
  result <- fm_build_data_params_map(
    SE = SE,
    data_source = data_source,
    data_obs = data_obs,
    samp_process = samp_process,
    b_constraint = b_constraint,
    cov_samp_process = cov_samp_process,
    const_spphab = const_spphab,
    biomass_temporal = biomass_temporal,
    sampling_temporal = sampling_temporal,
    anisotropy = anisotropy,
    lf_link = lf_link,
    b_com_i = b_com_i,
    mesh = mesh,
    time.step_df = time.step_df,
    loc_x = loc_x,
    y_com_i = y_com_i,
    y_sci_i = y_sci_i,
    cov_x_com = cov_x_com,
    cov_x_sci = cov_x_sci,
    xfb_x = xfb_x,
    c_com_x = c_com_x,
    t_com_i = t_com_i,
    weights_com = weights_com,
    t_sci_i = t_sci_i,
    spde = spde,
    Aix_ij_com = Aix_ij_com,
    Aix_w_com = Aix_w_com,
    Aix_ij_sci = Aix_ij_sci,
    Aix_w_sci = Aix_w_sci,
    cov_x_pred = cov_x_pred,
    Aix_ij_pred = Aix_ij_pred,
    Aix_w_pred = Aix_w_pred,
    W = W,
    n_survey = n_survey,
    MeshList_aniso = MeshList_aniso,
    EM = EM,
    ref_data = ref_data,
    month_ref = month_ref,
    Version = Version
  )
  
  #' @description Testing that fm_build_data_params_map return a list
  expect_type(object = result, "list")
  
  #' @description Testing names of the list
  expect_named(result, c("data", "map", "params", "random"))
  
})
