# WARNING - Generated by {fusen} from /dev/flat_main.Rmd: do not edit by hand

test_that("fm_fit_model works", {
  
  # You can test your model with another parameter k. By construction, the first test of a value of k will always pass. Do not use for CI. You have to run tests localy to stock the rds file
  
  if(Sys.getenv("FISHMAP_K_PARAM") != ""){
    k <- Sys.getenv("FISHMAP_K_PARAM")
  }else{
    k <- 0.25
  }
  
  # run part1
  fm_data_inputs <- fm_load_data(
    k = k
  )
  
  # run part2
  withr::with_seed(1234,{
    fm_model_results <- fm_fit_model(fm_data_inputs)
  })
  
    
  # save part2 outputs, one for each k tested
  if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS") == "TRUE") {
    # setup save dir, create it if necessary
    output_dir <- Sys.getenv("FISHMAP_OUTPUT_DIR")
    if (isFALSE(dir.exists(output_dir))){
      dir.create(output_dir)
    }
    # save output
    saveRDS(object = fm_model_results, file = file.path(output_dir, paste0("part2_output", k ,".rds")))
    saveRDS(object = fm_model_results, file = file.path(paste0("part2_output", k ,".rds")))
  }
  
  # check output is saved as rds
  if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS") == "TRUE") {
    output_dir <- Sys.getenv("FISHMAP_OUTPUT_DIR")
    expect_true(file.exists(file.path(output_dir, paste0("part2_output", k ,".rds"))))
  }
  
  # Check resultats of model 
  
  # is a list
  expect_type(object = fm_model_results,  "list")
  
  # check names
  
  expect_named(
    object = fm_model_results, 
    expected = c(
      "time.step_df", 
      "loc_x" ,      
      "report" ,   
      "samp_process", 
      "converge" )
    )
  
  # check types inside the list
  
  # could be a map2 maybe
  expect_s3_class(fm_model_results$time.step_df, "data.frame")
  expect_s3_class(fm_model_results$loc_x, "data.frame")
  expect_type(fm_model_results$report, "list")
  expect_type(fm_model_results$samp_process, "double")
  expect_type(fm_model_results$converge, "integer")
  
  # Checking the object
  
  expect_identical(
    object = fm_model_results,
    expected = readRDS(file.path(paste0("part2_output", k ,".rds")))
  )
  
  
})
