# WARNING - Generated by {fusen} from /dev/flat_main.Rmd: do not edit by hand

# load necessary libraries (can be from sourced files)
library(dplyr)
library(INLA)
library(ggplot2)
library(raster)
library(sf)
library(stringr)
library(tidyr)
library(TMB)

test_that("fm_load_data works", {
  
  # check function runs without error
  expect_error(object = fm_data_inputs <- fm_load_data(),
               regexp = NA)
  
  # check output is a list
  expect_true(object = inherits(x = fm_data_inputs,
                                what = "list"))
  
  # check output is saved as rds
  if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS") == "TRUE") {
    output_dir <- Sys.getenv("FISHMAP_OUTPUT_DIR")
    expect_true(file.exists(file.path(output_dir, "part1_output.rds")))
  }
  
})
