# WARNING - Generated by {fusen} from /dev/flat_main.Rmd: do not edit by hand

test_that("fm_load_data works", {
  
  # run function
  fm_data_inputs <- fm_load_data()
  
  # save part1 outputs
  if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS") == "TRUE") {
    # setup save dir, create it if necessary
    output_dir <- Sys.getenv("FISHMAP_OUTPUT_DIR")
    if (isFALSE(dir.exists(output_dir))){
      dir.create(output_dir)
    }
    # save output
    saveRDS(object = fm_data_inputs, file = file.path(output_dir, "part1_output.rds"))
  }
  
  # check output is a list
  expect_true(object = inherits(x = fm_data_inputs,
                                what = "list"))
  
  # check output is saved as rds
  if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS") == "TRUE") {
    output_dir <- Sys.getenv("FISHMAP_OUTPUT_DIR")
    expect_true(file.exists(file.path(output_dir, "part1_output.rds")))
  }
  
})
