# WARNING - Generated by {fusen} from /dev/flat_main.Rmd: do not edit by hand

test_that("fm_generate_graphs works", {
  
  test_resolution <- Sys.getenv("FISHMAP_TEST_RESOLUTION", unset = "small")
  
  # # run part1
  # fm_data_inputs <- fm_load_data()
  
  # run part2
  if(test_resolution == "small"){
    
    
    fm_model_results <- readr::read_rds(
      system.file(
        "examples",
        paste0("part2_output_", test_resolution , ".rds"),
        package = "FishMap")
    )
  }else if (test_resolution == "big"){
    # TODO add tests for high resolution
  }
  
  # run part3
  fm_graph_results <- fm_generate_graphs(fm_model_results)
  
  # save part3 outputs
  if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS") == "TRUE") {
    # setup save dir, create it if necessary
    output_dir <- Sys.getenv("FISHMAP_OUTPUT_DIR")
    if (isFALSE(dir.exists(output_dir))){
      dir.create(output_dir)
    }
    # save output
    saveRDS(object = fm_graph_results, file = file.path(output_dir, "part3_output.rds"))
  }
  
  # check output is a list
  expect_true(object = inherits(x = fm_graph_results,
                                what = "list"))
  
  # check pred_plot output is a ggplot object
  expect_equal(object = class(fm_graph_results[["pred_plot"]]),
               expected = c("gg", "ggplot"))
  
  # check output is saved as rds
  if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS") == "TRUE") {
    output_dir <- Sys.getenv("FISHMAP_OUTPUT_DIR")
    expect_true(file.exists(file.path(output_dir, "part3_output.rds")))
  }
  
})

test_that("Main functions work together", {
  
  # Set up params for the model
  
  # run part1
  survey_data_file <- system.file("original_data",
                                  "Solea_solea",
                                  "survey_data.Rdata",
                                  package = "FishMap"
  )
  
  vmslogbook_data_file <- system.file("original_data",
                                      "Solea_solea",
                                      "vmslogbook_data.Rdata",
                                      package = "FishMap"
  )
  
  study_domain_file <- system.file("original_data",
                                   "Solea_solea",
                                   "study_domain.Rdata",
                                   package = "FishMap"
  )
  
  fm_data_inputs <- fm_load_data(species = "Solea_solea",
                                 fleet = c("OTB_DEF_>=70_0","OTB_CEP_>=70_0","OTT_DEF_>=70_0"),
                                 fitted_data = "biomass",
                                 survey_data_file = survey_data_file,
                                 vmslogbook_data_file = vmslogbook_data_file,
                                 study_domain_file = study_domain_file,
                                 year_start = 2018,
                                 year_end = 2018,
                                 month_start = 11,
                                 month_end = 11,
                                 time_step = "Month",
                                 k = 0.25,
                                 grid_xmin = -6,
                                 grid_xmax = 0,
                                 grid_ymin = 42,
                                 grid_ymax = 48)
  
  
  #'@description Testing that fm_data_inputs return a named list for the next function
  test_list <- is.list(fm_data_inputs)
  test_name <- length(names(fm_data_inputs)) != 0 
  
  expect_true(test_list & test_name)
  
  #'@descripton Testing if `fm_fit_model` always work
  result_fit_model <- try(
    fm_fit_model(fm_data_inputs = fm_data_inputs,
                 SE = 1,
                 data_source = 1,
                 data_obs = 2,
                 samp_process = 0,
                 b_constraint = 2,
                 cov_samp_process = 0,
                 biomass_temporal = 1,
                 sampling_temporal = 0,
                 lf_link = 0,
                 ref_data = "com",
                 EM = "est_b",
                 month_ref = 1), 
    silent = TRUE)
  
  expect_true(
               !inherits(result_fit_model, "try-error"), 
               label = "`fm_fit_model` generate a error. Please check the core function or the returned objet of `fm_load_data`. Running function"
  )
  
  
  #'@descripton Testing if `fm_fit_model` always work
  result_graph <- try(fm_generate_graphs(result_fit_model), silent = TRUE)
  
  expect_true(
               !inherits(result_graph, "try-error"), 
               label = "`fm_generate_graphs` generate a error. Please check the core function or the returned objet of `fm_fit_model`. Running function"
  )
  
  #'@description testing output of `fm_generate_graphs`
  expect_type(result_graph, "list")
  expect_s3_class(result_graph[["pred_plot"]], "ggplot")
  
})
