# WARNING - Generated by {fusen} from /dev/flat_fm_generate_graphs.Rmd: do not edit by hand

test_that("fm_generate_graphs works", {
  
  test_resolution <- Sys.getenv("FISHMAP_TEST_RESOLUTION", unset = "small")
  
  # load part2
  if(test_resolution == "small"){
    
    
    fm_model_results <- readr::read_rds(
      system.file(
        "examples",
        paste0("part2_output_", test_resolution , ".rds"),
        package = "FishMap")
    )
  }else if (test_resolution == "big"){
    
    fm_model_results <- readr::read_rds(
      file.path(
        "data", 
        paste0("part2_output_", test_resolution , ".rds")
      )
    )
  }
  
  # run part3
  fm_graph_results <- fm_generate_graphs(fm_model_results)
  
  # Update expected outputs here
  if (Sys.getenv("FISHMAP_UPDATE_TEST_OUTPUTS") == "TRUE") {
    # save output depending if we are in flat or in test
    output_inst_dir <- here::here("inst", "examples") 
    
    if (test_resolution == "small") {
      readr::write_rds(x = fm_graph_results,
                       file = file.path(output_inst_dir, paste0("part3_output_", test_resolution , ".rds")))
    }else if (test_resolution == "big") {
      ## TODO what we need to check
      readr::write_rds(x = fm_graph_results,
                       file = file.path(
                         "data", 
                         paste0("part3_output_", test_resolution , ".rds")
                       )
      )
    }
    
  }
  
  # check output is saved as rds
  if (Sys.getenv("FISHMAP_UPDATE_TEST_OUTPUTS") == "TRUE") {
    
    output_inst_dir <- here::here("inst", "examples")
    
    if (test_resolution == "small") {
      #' @description Test to check if we can save output small
      expect_true(file.exists(file.path(output_inst_dir, paste0("part3_output_", test_resolution , ".rds"))))
    }else if (test_resolution == "big") {
      #' @description Test to check if we can save output big
      expect_true(file.exists(file.path(
        "data", 
        paste0("part3_output_", test_resolution , ".rds")
      )
      )
      )
    }
    
  }
  
  # Check results of model 
  
  #' @description Testing the result of `fm_generate_graphs()` is a list
  expect_true(object = inherits(x = fm_graph_results,
                                what = "list"))
  
  #' @description Testing class of the pred plot returned by `fm_generate_graphs()` 
  expect_s3_class(
    object = fm_graph_results[["pred_plot"]],
    class = c("gg", "ggplot")
    )
  
  # Testing for small model
  if(test_resolution == "small"){
    # Testing that the result of `fm_generate_graphs()` is stable
    # Currently not working in CI
    # expected_outputs <- readr::read_rds(
    #   system.file(
    #     "examples",
    #     paste0("part3_output_", test_resolution , ".rds"),
    #     package = "FishMap")
    # )
    # 
    # expect_equal(
    #   object = fm_graph_results,
    #   expected = expected_outputs,
    #   tolerance = 1e-4
    # )
  }

})
