# WARNING - Generated by {fusen} from /dev/flat_main.Rmd: do not edit by hand

test_that("fm_fit_model works", {
  
  # You can test your model with another parameter k. By construction, the first test of a value of k will always pass. Do not use for CI. You must run the tests locally with FISHMAP_UPDATE_OUTPUTS env at TRUE to store the rds file.
  
  if(Sys.getenv("FISHMAP_K_PARAM") != ""){
    k <- as.numeric(Sys.getenv("FISHMAP_K_PARAM"))
  }else{
    k <- 0.25
  }
  
  # run part1
  survey_data_file <- system.file("original_data",
                                  "Solea_solea",
                                  "survey_data.Rdata",
                                  package = "FishMap"
  )
  
  vmslogbook_data_file <- system.file("original_data",
                                      "Solea_solea",
                                      "vmslogbook_data.Rdata",
                                      package = "FishMap"
  )
  
  study_domain_file <- system.file("original_data",
                                   "Solea_solea",
                                   "study_domain.Rdata",
                                   package = "FishMap"
  )
  
  fm_data_inputs <- fm_load_data(species = "Solea_solea",
                                 fleet = c("OTB_DEF_>=70_0","OTB_CEP_>=70_0","OTT_DEF_>=70_0"),
                                 fitted_data = "biomass",
                                 survey_data_file = survey_data_file,
                                 vmslogbook_data_file = vmslogbook_data_file,
                                 study_domain_file = study_domain_file,
                                 year_start = 2018,
                                 year_end = 2018,
                                 month_start = 11,
                                 month_end = 11,
                                 time_step = "Month",
                                 k = k,
                                 grid_xmin = -6,
                                 grid_xmax = 0,
                                 grid_ymin = 42,
                                 grid_ymax = 48)
  
  # run part2
  withr::with_seed(1234,{
    fm_model_results <- fm_fit_model(fm_data_inputs)
  })
  
    
  # save part2 outputs, one for each k tested
  if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS") == "TRUE") {
    # setup save dir, create it if necessary
    output_dir <- Sys.getenv("FISHMAP_OUTPUT_DIR")
    if (isFALSE(dir.exists(output_dir))){
      dir.create(output_dir)
    }
    # save output
    saveRDS(object = fm_model_results, file = file.path(output_dir, paste0("part2_output", k ,".rds")))
    
    # TODO To reduce size of the rds, we have to only save some parts, not all
    # saveRDS(object = fm_model_results, file = file.path(paste0("part2_output", k ,".rds")))
  }

  
  # check output is saved as rds
  if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS") == "TRUE") {
    output_dir <- Sys.getenv("FISHMAP_OUTPUT_DIR")
    
    #' @description Test to check if we can save output
    expect_true(file.exists(file.path(output_dir, paste0("part2_output", k ,".rds"))))
  }
  
  # Check resultats of model 
  
  #' @description Testing the result of `fm_fit_model` is a list
  expect_type(object = fm_model_results,  "list")
  
  #' @description Testing names of the list return by `fm_fit_model` 
  expect_named(
    object = fm_model_results, 
    expected = c(
      "time.step_df", 
      "loc_x" ,      
      "report" ,   
      "samp_process", 
      "converge" )
    )
  
  
  #' @description Testing types inside the list return by `fm_fit_model` 
  expect_s3_class(fm_model_results$time.step_df, "data.frame")
  expect_s3_class(fm_model_results$loc_x, "data.frame")
  expect_type(fm_model_results$report, "list")
  expect_type(fm_model_results$samp_process, "double")
  expect_type(fm_model_results$converge, "integer")
  
  # TODO To reduce size of the rds, we have to check only some parts
  # #' @description Testing that the result of `fm_fit_model` is stable
  # expect_equal(
  #   object = fm_model_results,
  #   expected = readRDS(file.path(paste0("part2_output", k ,".rds")))
  # )
  
})
