# WARNING - Generated by {fusen} from /dev/flat_fm_generate_graphs.Rmd: do not edit by hand

#' generate output graphs
#' 
#' @param fm_model_results list Named list obtained from `fm_fit_model()`
#' 
#' @importFrom dplyr mutate inner_join
#' @importFrom ggplot2 ggplot geom_sf aes scale_color_distiller facet_wrap
#' @importFrom sf st_as_sf
#' @importFrom stringr str_replace
#' @importFrom tictoc tic toc
#' @importFrom tidyr pivot_longer starts_with
#' @importFrom rgdal projInfo
#' 
#' @return list A named list of all generated graphs (step 3)
#' 
#' @export
#' @examples
#' \donttest{
#' 
#' # loading `fm_fit_model()` outputs
#' fm_fit_model_outputs <- readr::read_rds(
#'   system.file("examples", "part2_output_small.rds",
#'               package = "FishMap")
#'   )
#' 
#' # run function
#' fm_generate_graphs(fm_model_results = fm_fit_model_outputs)
#' 
#' }
fm_generate_graphs <- function(fm_model_results) {
  ## Plot model outputs
  #--------------------
  message("Running step 4 -plot graphs-")
  tic("Step 4 -plot graphs-")
  
  ## Dependencies from Part1 factorization
  loc_x <- fm_model_results[["loc_x"]]
  time.step_df <- fm_model_results[["time.step_df"]]
  report <- fm_model_results[["report"]]
  samp_process <- fm_model_results[["samp_process"]]
  
  if (nrow(time.step_df) > 1) {
    pred_df <-
      cbind(loc_x[, c("long", "lati")], S_x = report$S_p[1:nrow(loc_x), ]) %>%
      pivot_longer(cols = starts_with("S_x."),
                   names_to = "t",
                   values_to = "S_x") %>%
      mutate(t = as.numeric(str_replace(t, "S_x.", ""))) %>%
      inner_join(time.step_df)
    
    pred_sf <- st_as_sf(pred_df, coords = c("long", "lati"))
    
    pred_plot <- ggplot(pred_sf) +
      geom_sf(aes(col = S_x)) +
      scale_color_distiller(palette = "Spectral") +
      facet_wrap(. ~ Year_Month)
    
    
  } else if (nrow(time.step_df) == 1) {
    pred_df <-
      cbind(loc_x[, c("long", "lati")], S_x = report$S_p[1:nrow(loc_x), ])
    
    pred_sf <- st_as_sf(pred_df, coords = c("long", "lati"))
    
    pred_plot <- ggplot(pred_sf) +
      geom_sf(aes(col = S_x)) +
      scale_color_distiller(palette = "Spectral")
    
  }
  
  plot(pred_plot)
  
  # plot eta if sampling is active
  if (samp_process == 1) {
    for (i in 1:3) {
      eta_df <-
        cbind(loc_x[, c("long", "lati")], eta = report$lambda_p[1:nrow(loc_x), , i]) %>%
        pivot_longer(
          cols = starts_with("eta."),
          names_to = "t",
          values_to = "eta"
        ) %>%
        mutate(t = as.numeric(str_replace(t, "eta.", ""))) %>%
        inner_join(time.step_df)
      
      eta_sf <- st_as_sf(eta_df, coords = c("long", "lati"))
      
      eta_plot <- ggplot(eta_sf) +
        geom_sf(aes(col = log(eta))) +
        scale_color_distiller(palette = "Spectral") +
        facet_wrap(. ~ Year_Month)
      
      plot(eta_plot)
    }
  }
  
  # finished step 4 -plot graph-
  toc()
  
  # return outputs as named list
  output_list <- list("pred_plot" = pred_plot)
  
  # return eta plot if sampling is on
  if (samp_process == 1) {
    output_list[["eta_plot"]] <- eta_plot
  }
  return(output_list)
  
}
