# WARNING - Generated by {fusen} from /dev/flat_fm_load_data.Rmd: do not edit by hand

#' Load and prepare data for model fitting
#'
#' @param species character Species of interest
#' @param fleet character Fleet chosen according to the species of interest. A fleet is considered to have homogeneous catchability and targeting behavior.
#' @param fitted_data character Type of the data to be fitted to the model (either `biomass` for biomass data - positive-continuous data - or `presabs` for presence-absence data). Default is `biomass`
#' @param survey_data data.frame Dataframe containing the scientific (survey) data
#' @param vmslogbook_data  data.frame Dataframe containing the commercial (vmslogbook) data
#' @param study_domain  data.frame Dataframe containing the data describing the study area
#' @param year_start integer Starting year
#' @param year_end integer Ending year
#' @param month_start integer Starting month
#' @param month_end integer Ending month
#' @param time_step character Time step for the model (either `Month` for monthly time step or `Quarter` for quarterly time step). Default is `Month`
#' @param k numeric Parameter controlling the number of knots of the mesh. The higher the denser.
#' @param grid_xmin,grid_xmax,grid_ymin,grid_ymax  numeric Limitation of the grid for the spatial domain
#' @param seed integer The seed controlling for random effect. Default is 29510.
#'
#' @importFrom dplyr ungroup select filter arrange mutate
#' @importFrom stringr str_detect
#' @importFrom tictoc tic toc
#' @importFrom withr local_seed
#'
#' @return list A named list of all necessary outputs for model fitting (`fm_fit_model()`)
#' @export
#'
#' @examples
#' \donttest{
#' # run part1
#' survey_data_file <- system.file("original_data",
#'                                 "Solea_solea",
#'                                 "survey_data.Rds",
#'                                 package = "FishMap"
#' )
#'
#' survey_data <- readr::read_rds(file = survey_data_file)
#'
#' vmslogbook_data_file <- system.file("original_data",
#'                                     "Solea_solea",
#'                                     "vmslogbook_data.Rds",
#'                                     package = "FishMap"
#' )
#'
#' vmslogbook_data <- readr::read_rds(file = vmslogbook_data_file)
#'
#' study_domain_file <- system.file("original_data",
#'                                  "Solea_solea",
#'                                  "study_domain.Rds",
#'                                  package = "FishMap"
#' )
#'
#' study_domain <- readr::read_rds(file = study_domain_file)
#'
#' fm_data_inputs <- fm_load_data(species = "Solea_solea",
#'                                fleet = c("OTB_DEF_>=70_0","OTB_CEP_>=70_0","OTT_DEF_>=70_0"),
#'                                fitted_data = "biomass",
#'                                survey_data = survey_data,
#'                                vmslogbook_data = vmslogbook_data,
#'                                study_domain = study_domain,
#'                                year_start = 2018,
#'                                year_end = 2018,
#'                                month_start = 11,
#'                                month_end = 11,
#'                                time_step = "Month",
#'                                k = 0.25,
#'                                grid_xmin = -6,
#'                                grid_xmax = 0,
#'                                grid_ymin = 42,
#'                                grid_ymax = 48)
#' }
fm_load_data <- function(species,
                         fleet,
                         fitted_data = c("biomass","presabs"),
                         survey_data,
                         vmslogbook_data,
                         study_domain,
                         year_start,
                         year_end,
                         month_start,
                         month_end,
                         time_step = c("Month","Quarter"),
                         k,
                         grid_xmin,
                         grid_xmax,
                         grid_ymin,
                         grid_ymax,
                         seed = 29510
) {
  ## Load data
  #-----------
  message("Running step 1 -loading data-")
  tic("Step 1 -loading data-")

  # set seed
  local_seed(seed = seed)

  # check input values
  fitted_data <- match.arg(fitted_data)
  time_step <- match.arg(time_step)

  # Scientific data
  n_survey <- 1 # number of surveys
  scientific_observation <- "CPUE" # 'CPUE' or 'Density'
  survey_data_0 <- survey_data %>% ungroup %>% dplyr::select(-layer)

  # 'VMS x logbook' data
  select_aggreg_level <- paste(fleet,collapse = "|")
  vmslogbook_data <- vmslogbook_data %>%
    filter(str_detect(LE_MET_level6,select_aggreg_level))

  vmslogbook_data$LE_MET_level6 <- factor(as.character(vmslogbook_data$LE_MET_level6),levels = fleet)

  vmslogbook_data_0 <- vmslogbook_data %>% ungroup %>% dplyr::select(-layer)

  ## Time series
  #-------------
  year_vec <- year_start:year_end
  month_vec <- month_start:month_end

  if(time_step == "Month"){

    time.step_df <- expand.grid(month_vec,year_vec)
    colnames(time.step_df) <- c("Month","Year")

    time.step_df <- time.step_df %>%
      arrange(Year,Month) %>%
      mutate(Month = ifelse(Month < 10,paste0("0",Month),Month)) %>%
      mutate(Year_Month = paste0(Year,"_",Month)) %>%
      mutate(t = 1:nrow(time.step_df))
    time.step_df$Year <- as.character(time.step_df$Year)
    time.step_df$Month <- as.character(time.step_df$Month)

  }else if(time_step == "Quarter"){

    time.step_df <- expand.grid(1:4,all_years)
    colnames(time.step_df) <- c("Quarter","Year")

    time.step_df <- time.step_df %>%
      arrange(Year,Quarter) %>%
      mutate(Quarter = ifelse(Quarter < 10,paste0("0",Quarter),Quarter)) %>%
      mutate(Year_Quarter = paste0(Year,"_",Quarter)) %>%
      mutate(t = 1:nrow(time.step_df))
    time.step_df$Year <- as.character(time.step_df$Year)
    time.step_df$Quarter <- as.character(time.step_df$Quarter)

  }


  ## Configure spatial domain
  #--------------------------
  grid_xmin <- grid_xmin
  grid_xmax <- grid_xmax
  grid_ymin <- grid_ymin
  grid_ymax <- grid_ymax

  grid_limit <- raster::extent(
    c(grid_xmin,
      grid_xmax,
      grid_ymin,
      grid_ymax)
  )

  grid_projection <- "+proj=longlat +datum=WGS84"

  resol <- 0.05 # resolution of the discretization grid
  create_mesh <- "from_shapefile"
  # from_shapefile: the mesh will be more regular on the grid
  # from_data: the mesh will be denser in the areas where there are data

  # Mesh parameterization
  # reduce the mesh size (k = 0.25 now) reduces the number of knots at which the spatial random effect is computed.
  k <- k
  Alpha <- 2

  ## Load domain / mesh / spde object
  domain_mesh_spde_outputs <- fm_build_domain_mesh_spde(
    grid_limit = grid_limit,
    resol = resol,
    grid_projection = grid_projection,
    study_domain = study_domain,
    create_mesh = create_mesh,
    k = k,
    vmslogbook_data = vmslogbook_data,
    Alpha = Alpha
  )

  ## Shape scientific data
  sci_data_st_outputs <- fm_shape_sci_data_st(
    survey_data_0 = survey_data_0,
    time.step_df = time.step_df,
    grid_projection = grid_projection,
    gridpolygon_sf = domain_mesh_spde_outputs[["gridpolygon_sf"]],
    scientific_observation = scientific_observation,
    Sci.obs_spp = Sci.obs_spp,
    mesh = domain_mesh_spde_outputs[["mesh"]]
  )

  ## Shape commercial data
  vms_logbook_data_st_outputs <- fm_shape_vms_logbook_data_st(
    vmslogbook_data_0 = vmslogbook_data_0,
    time.step_df = time.step_df,
    grid_projection = grid_projection,
    gridpolygon_sf = domain_mesh_spde_outputs[["gridpolygon_sf"]],
    loc_x = domain_mesh_spde_outputs[["loc_x"]],
    mesh = domain_mesh_spde_outputs[["mesh"]]
  )

  if(fitted_data=="presabs"){

    transf_vec = vms_logbook_data_st_outputs[["y_com_i"]]
    transf_vec[which(transf_vec > 0)] <- 1
    vms_logbook_data_st_outputs[["y_com_i"]] = transf_vec

    transf_vec = sci_data_st_outputs[["y_sci_i"]]
    transf_vec[which(transf_vec > 0)] <- 1
    sci_data_st_outputs[["y_sci_i"]] = transf_vec

  }


  ## Covariates
  #------------
  # load(file.path(data_folder,"bathy_pred.Rdata"))
  bathy_pred = rep(0,nrow(domain_mesh_spde_outputs[["loc_x"]]))
  cov_x_pred <- matrix(data = bathy_pred, ncol = 1)

  # load(file.path(data_folder,"bathy_com.Rdata"))
  bathy_com = rep(0,nrow(vms_logbook_data_st_outputs[["vmslogbook_data_2"]]))
  cov_x_com <- matrix(data = bathy_com, ncol = 1)

  # load(file.path(data_folder,"bathy_sci.Rdata"))
  bathy_sci = rep(0,nrow(sci_data_st_outputs[["survey_data_2"]]))
  cov_x_sci <- matrix(data = bathy_sci, ncol = 1)

  # finished step 1 -loading data-
  toc()

  # return outputs as named list
  return(list("species" = species,
              "b_com_i" = vms_logbook_data_st_outputs[["b_com_i"]],
              "mesh" = domain_mesh_spde_outputs[["mesh"]],
              "time.step_df" = time.step_df,
              "loc_x" = domain_mesh_spde_outputs[["loc_x"]],
              "y_com_i" = vms_logbook_data_st_outputs[["y_com_i"]],
              "y_sci_i" = sci_data_st_outputs[["y_sci_i"]],
              "cov_x_com" = cov_x_com,
              "cov_x_sci" = cov_x_sci,
              "c_com_x" = vms_logbook_data_st_outputs[["c_com_x"]],
              "t_com_i" = vms_logbook_data_st_outputs[["t_com_i"]],
              "t_sci_i" = sci_data_st_outputs[["t_sci_i"]],
              "spde" = domain_mesh_spde_outputs[["spde"]],
              "Aix_ij_com" = vms_logbook_data_st_outputs[["Aix_ij_com"]],
              "Aix_w_com" = vms_logbook_data_st_outputs[["Aix_w_com"]],
              "Aix_ij_sci" = sci_data_st_outputs[["Aix_ij_sci"]],
              "Aix_w_sci" = sci_data_st_outputs[["Aix_w_sci"]],
              "cov_x_pred" = cov_x_pred,
              "Aix_ij_pred" = domain_mesh_spde_outputs[["Aix_ij_pred"]],
              "Aix_w_pred" = domain_mesh_spde_outputs[["Aix_w_pred"]],
              "W" = domain_mesh_spde_outputs[["W"]],
              "n_survey" = n_survey,
              "MeshList_aniso" = domain_mesh_spde_outputs[["MeshList_aniso"]]
  )
  )
}
