# WARNING - Generated by {fusen} from /dev/flat_fm_load_data.Rmd: do not edit by hand

#' Shape scientific data
#'
#' @importFrom dplyr mutate inner_join ungroup select
#' @importFrom INLA inla.spde.make.A
#' @importFrom sf st_as_sf st_intersects st_join st_coordinates
#'
#' @param survey_data_0 tibble Scientific data
#' @param time.step_df data.frame Time window used
#' @param grid_projection character A character string of projection arguments for `sp::CRS()`
#' @param gridpolygon_sf sf data.frame Spatialpolygon based on raster
#' @param scientific_observation character Measure unit of scientific observation (either `CPUE` or `Density`). Default is `CPUE`
#' @param Sci.obs_spp data.frame Scientific observation data, used when scientific observation unit is `Density`
#' @param mesh inla.mesh Spatial grid of observations
#'
#' @return list A named list
#'
#' @noRd
#' @examples
#' \dontrun{
#' # fm_shape_sci_data_st(
#' #   survey_data_0 = survey_data_0,
#' #   time.step_df = time.step_df,
#' #   grid_projection = "+proj=longlat +datum=WGS84",
#' #   gridpolygon_sf = domain_mesh_spde_outputs[["gridpolygon_sf"]],
#' #   scientific_observation = "CPUE",
#' #   Sci.obs_spp = NULL,
#' #   mesh = domain_mesh_spde_outputs[["mesh"]]
#' # )
#' }
fm_shape_sci_data_st <- function(
    survey_data_0,
    time.step_df,
    grid_projection,
    gridpolygon_sf,
    scientific_observation = c("CPUE", "Density"),
    Sci.obs_spp,
    mesh
) {
  ## Shape date columns
  survey_data_0$Month <- as.character(survey_data_0$Month)
  survey_data_0$Year <- as.character(survey_data_0$Year)

  ## Join scientific data with time step data frame
  survey_data_1 <- survey_data_0 %>%
    mutate(Month = ifelse(Month %in% paste0(1:9),
                          paste0("0",Month),paste0(Month))) %>%
    inner_join(time.step_df)

  ## Convert commercial data into sf object to intersect with gridpolygon
  survey_data_sf <- st_as_sf(survey_data_1,
                             coords = c("long","lati"),
                             crs = grid_projection) %>%
    ungroup()

  ## Discretize scientific data
  survey_data_sf <- survey_data_sf[st_intersects(survey_data_sf,gridpolygon_sf) %>% lengths > 0,]
  survey_data_2 <- st_join(survey_data_sf,gridpolygon_sf) %>%
    mutate(long = st_coordinates(.)[,1],
           lati = st_coordinates(.)[,2]) %>%
    as.data.frame() %>%
    dplyr::select(-geometry)

  survey_data_2$Sci.obs_spp <- survey_data_2$CatchWgt_spp/survey_data_2$HaulDur

  y_sci_i <- survey_data_2$Sci.obs_spp # scientific observation
  t_sci_i <- survey_data_2$t # time step

  ## Mesh objects for scientific data
  A <- inla.spde.make.A(mesh, loc=as.matrix(survey_data_2[,c("long","lati")] ))
  A <- as( A, "dgTMatrix")
  Aix_ij_sci <- cbind(A@i,A@j)
  Aix_w_sci <- A@x

  # Return named list as output
  return(
    list(
      "y_sci_i" = y_sci_i,
      "t_sci_i" = t_sci_i,
      "Aix_ij_sci" = Aix_ij_sci,
      "Aix_w_sci" = Aix_w_sci,
      "survey_data_2" = survey_data_2
    )
  )
}
